### ISSUE TITLE
Upgrade workflow

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard-development-handbook#4]
Follow the [governance process](http://standard.open-contracting.org/latest/en/support/governance/#revision-process) throughout.

1. Create [issues](https://github.com/open-contracting/standard/issues) on the 'standard' GitHub repository
1. Collect the issues into a [milestone](https://github.com/open-contracting/standard/milestones) named 'Version X.X'
1. Write [pull requests](https://github.com/open-contracting/standard/pulls) to resolve issues with the proposed new schema and documentation, or stage changes as extensions for additional fields
1. Travis builds the documentation and SFTP's the branch’s documentation
1. Add new core and community extensions to the [extension_registry](https://github.com/open-contracting/extension_registry)
1. Update tools (we should be more specific about what must be changed)
    * CoVE only needs to be updated to support new schema features
    * [ocds-faker](https://github.com/open-contracting/ocds-faker) (Node.js)
    * [ocds-show](https://github.com/open-contracting/ocds-show) (Node.js)
    * [ocds-show-ppp](https://github.com/open-contracting/ocds-show-ppp) (Node.js)
    * [sample-data](https://github.com/open-contracting/sample-data) (Python)
    * [extension_creator](https://github.com/open-contracting/extension_creator) (Node.js)
    * [standard_extension_template](https://github.com/open-contracting/standard_extension_template)
1. Update SVGs and PNGs manually, as needed
1. Translate documentation and schema
1. Tag and release core extensions
1. Launch new version of standard

Consider whether to add release candidates to our process, considering people are already using unreleased versions.

----

# Tasks

* [x] Fill in gaps in the above
* [x] When do we update SVGs, PNGs, etc.?
* [x] Add more documentation about staging changes as extensions for additional fields
  * http://ocds-standard-development-handbook.readthedocs.io/en/latest/extensions/
* [x] Add documentation about updating existing extensions to work with new standard version
  * http://ocds-standard-development-handbook.readthedocs.io/en/latest/standard/technical/deployment/#pin-extensions
* [x] Add documentation about non-master branches of `extension_registry`
  * http://ocds-standard-development-handbook.readthedocs.io/en/latest/standard/technical/deployment/#pin-extensions

Cleanup:
* [x] Check web analytics to see if people are visiting old branch versions of documentation
  * http://ocds-standard-development-handbook.readthedocs.io/en/latest/github/branch_management/
* [x] Decide whether to have a schedule for deleting old, unvisited versions
  * http://ocds-standard-development-handbook.readthedocs.io/en/latest/github/branch_management/

Questions:
* [x] Where does the documentation corresponding to the pull request's branch become available?
  * http://ocds-standard-development-handbook.readthedocs.io/en/latest/standard/technical/deployment/#build-on-travis

**Comment by Bjwebb** [comment]
@robredpath Could you compare the list above with what came out of 1.1 retro at Wortley.

>  When do we updating SVGs, PNGs, etc.?

I'm not sure if we do this atm. Although most images are vague enough that I'm not sure they've needed updating.

**Comment by timgdavies** [comment]
On the question "Where does the documentation corresponding to the pull request's branch become available?"  I think the answer might be http://standard.open-contracting.org/{branch-name}/ 

E.g. http://standard.open-contracting.org/fix-amendment-guidance-link/ is a build of that branch, triggered as soon as it is pushed, and usually available in 5 - 10 minutes.

**Comment by timgdavies** [comment]
On the question of SVGs and PNGs, this has been manual process.

However, I would like to explore how we could move towards everything as SVG and set-up in a way that can be part of our translation workflow as well.

**Comment by robredpath** [comment]
Apologies, I missed the alerts for this and only saw it when I went to review my assigned issues! 

We mapped out the upgrade process with flipchart and post-its when we met over the summer to carry out a retro on the 1.1 upgrade:

![img_0281](https://user-images.githubusercontent.com/641009/31995940-61508872-b97e-11e7-8d6d-03114f1469d2.jpg)

At the time, we incorporated the governance process into the upgrade process (hence why there's post-its for 'peer review', for example), and I think that's helpful when you're actually in the process, to know what you need to do with all of the input you get and outputs you create. I'm not sure if it's possible to look at the upgrade process and the governance process separately, or to frame one within the other, as I think they may just be too intertwined.

**Comment by jpmckinney** [comment]
Based on progress made since this issue was opened, I'll re-scope and break it up. There are still some tasks in the issue description that are relevant, but maybe better to pursue as smaller issues.

**Comment by jpmckinney** [comment]
I think the content suggested in this issue already resides at:

http://standard.open-contracting.org/latest/en/support/governance/
http://ocds-standard-development-handbook.readthedocs.io/en/latest/standard/technical/deployment/
http://ocds-standard-development-handbook.readthedocs.io/en/latest/tools/#ocds-extension-support
